### ISSUE TITLE
Give "Create an Event" form the required fields

### ISSUE THREAD

**Issue by jeffmcq1616** [spring-giant/mgt656-spring-2015-project#15]
As a user I can visit your page for creating new events at /events/new

It should have a form for creating events. The form should have attribute method="POST".
I must specify the following attributes of an event: title, location, image, year, month, day, hour, and minute.
There must be a form element with name= for each of these, where "" is title, location, etc.
Every form element requires a label element with appropriate for attribute.
The year, month, day, hour, and minute form elements should be select elements.
The minute should only have 0, and 30 as selections. (At the hour and half hour).
The hour select should be in 24-hour time format: 0-23 are selectable.
The month select should have integer value attributes and refer to months by their names: January, February, etc.
You should only be able to schedule events in 2015 and 2016

**Comment by peapumpkin** [comment]
events.js already has a lot already there, need to talk to TA about what parts of the form we need to create vs. what's already coded.

**Comment by peapumpkin** [comment]
This is complete on my end, just needs to be merged in.

**Comment by meghaghildyal** [comment]
Great job Lea.. next step would be to start playing around with the style (css) elements..

**Comment by peapumpkin** [comment]
For report: 
-- Ran mocha, and the test for 'new event creation page should exist' and 'form that can be posted back' already passed, so did not need to create the page.
-- Requirements for this user story were that user must specify the following attributes of an event: title, location, image, year, month, day, hour, and minute.
-- In html for create-event page, the field for title already existed.
-- By copying and editing the title field code, created fields for location, image, year, month, day, hour, and minute.
-- All 3 tests now pass for event creation page.
-- This did not take as long as anticipated because broke up this big user story into smaller user stories. First, just created the form fields. Next, need to make them functional by adding form validation and then add CSS formatting.

**Comment by meghaghildyal** [comment]
Lea.. the Create New Event page is down: https://mgt656-spring-giant.herokuapp.com/ . We have submitted this link to the TAs recently, they will be checking it with the new sprint report. Can you do troubleshooting on this asap? Thanks
